### ISSUE TITLE
Cannot find type 'SliderStyle' in scope

### ISSUE THREAD

**Issue by yujinqiu** [Kyle-Ye/SwiftUIPostDemo#1]
When I try to run this demo on my iOS 17 physical device,  Xcode show error:
```
Cannot find type 'SliderStyle' in scope
```

**Comment by Kyle-Ye** [comment]
The repo only supports iOS Simulator for demonstration. For iOS device build, you need to modify the repo a bit to add the corresponding framework/tbd files.

**Comment by Kyle-Ye** [comment]
- iOS Simulator's SwiftUI btd file is bundled in the simruntime.
	- eg. `/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 15.5.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/SwiftUI.framework`

To get iOS's SwiftUI btd file:
1. Download one from Internet at your risk.
	- eg. https://github.com/xybp888/iOS-SDKs/blob/master/iPhoneOS17.0.sdk/System/Library/Frameworks/SwiftUI.framework/SwiftUI.tbd)

2. Or connect your iOS 17 device to get the SwiftUI binary from the corresponding iOS DeviceSupport bundle. And create a tbd file from the binary via [`tbd`](https://github.com/inoahdev/tbd) or `xcrun tapi`
	- eg. Located at `~/Library/Developer/Xcode/iOS DeviceSupport/iPhone16,1 17.2.1 (21C66)/Symbols/System/Library/Frameworks/SwiftUI.framework/SwiftUi`)

When you are done replace the framework with the new one. Then you can build it with iOS SDK.

If you'd like to support iOS and iOS Simulator at the same time, you need to mock it as a SwiftUI.xcframework.

See https://github.com/OpenSwiftUIProject/OpenGraph/tree/main/AG for more tip.
